// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRiVlqHzCJZEj0n-Y082pBxS2QrgZLYdQ',
    appId: '1:211435287671:web:9edfca9c0eda79c80f4272',
    messagingSenderId: '211435287671',
    projectId: 'verbal-virtuosos-debate-a-thon',
    authDomain: 'verbal-virtuosos-debate-a-thon.firebaseapp.com',
    storageBucket: 'verbal-virtuosos-debate-a-thon.appspot.com',
    measurementId: 'G-TVH892ZY1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX5eqNDE292cGrvoc3pIcC0ksinWmfh8k',
    appId: '1:211435287671:android:9abdc686bcd74d3b0f4272',
    messagingSenderId: '211435287671',
    projectId: 'verbal-virtuosos-debate-a-thon',
    storageBucket: 'verbal-virtuosos-debate-a-thon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoYpj3nuFayAbuOkQotHdPWc3mXNGzjA0',
    appId: '1:211435287671:ios:3a696769464deb880f4272',
    messagingSenderId: '211435287671',
    projectId: 'verbal-virtuosos-debate-a-thon',
    storageBucket: 'verbal-virtuosos-debate-a-thon.appspot.com',
    iosBundleId: 'com.example.hackathonTark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoYpj3nuFayAbuOkQotHdPWc3mXNGzjA0',
    appId: '1:211435287671:ios:64dd1b955d354ae30f4272',
    messagingSenderId: '211435287671',
    projectId: 'verbal-virtuosos-debate-a-thon',
    storageBucket: 'verbal-virtuosos-debate-a-thon.appspot.com',
    iosBundleId: 'com.example.hackathonTark.RunnerTests',
  );
}
